//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.15 at 10:01:22 AM MSD 
//


package com.googlecode.dtools.typeinfo.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for domainEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="domainEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="GENERAL"/>
 *     &lt;enumeration value="CUSTOM"/>
 *     &lt;enumeration value="APPLICATION"/>
 *     &lt;enumeration value="INTERNAL"/>
 *     &lt;enumeration value="SYSTEM"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "domainEnum")
@XmlEnum
public enum DomainEnum {

    GENERAL,
    CUSTOM,
    APPLICATION,
    INTERNAL,
    SYSTEM;

    public String value() {
        return name();
    }

    public static DomainEnum fromValue(String v) {
        return valueOf(v);
    }

}
